// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using task_manager_api.Data;

#nullable disable

namespace task_manager_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031081741_UpdateModelsAndSeeding")]
    partial class UpdateModelsAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("task_manager_api.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("TaskId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("task_manager_api.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69c9d9a8-aa4d-4d6f-90ee-57529d3e835e"),
                            IsDone = false,
                            Score = 0m,
                            Status = 0,
                            Title = "Sample Task – finish the report"
                        });
                });

            modelBuilder.Entity("task_manager_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$.WP2DZxs.kYpmwC0OHWEzORqmSWD.dHIdSbN/Gkjjh6q3y7Ej4gMW",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("2da95f81-f170-40ce-8e09-fb1d3e16b260"),
                            Email = "evaluator@example.com",
                            Name = "Evaluator User",
                            PasswordHash = "$2a$11$CnemFt7zfbT1rKqpEXeVbu3qluWjTqGbL9vIcHjhTsH.tf5hGOKom",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("643dc815-8b58-494c-8353-7a2329b07fd6"),
                            Email = "employee@example.com",
                            Name = "Employee User",
                            PasswordHash = "$2a$11$g8HGMbfKDe7fqCeXRJRlJucZuEF20RKMKkNydHO77Pyr19p3e4zeC",
                            Role = 2
                        });
                });

            modelBuilder.Entity("task_manager_api.Models.Evaluation", b =>
                {
                    b.HasOne("task_manager_api.Models.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("task_manager_api.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("task_manager_api.Models.TaskItem", b =>
                {
                    b.HasOne("task_manager_api.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");
                });
#pragma warning restore 612, 618
        }
    }
}
